### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [cmpsc100-allegheny-college/powerplant-jjumadinova#2]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Paperwork

- [ ] No TODO markers left in reflection.md
- [ ] All checkboxes checked in reflection.md

## Control Room

- [ ] No TODO markers left in the main.py file
- [ ] main.py imports all available power sources (even if not using them)
- [x] main.py creates function for charge_battery with complete signature
- [x] main.py calls charge_battery with complete call
- [x] main.py uses JSON library to read from .battery
- [x] main.py uses JSON library to write to .battery
- [x] main.py calls either the power or energy property

## Diversification

- [ ] Neighborhood diversified power generation to use at least one inexhaustible
- [x] SolarField sets the wattage property of the solar panel
- [ ] WindFarm sets the turbine blade size

## Inheritance

- [x] Inexhaustible source (SolarField) uses inheritance
- [ ] Inexhaustible source (WindFarm) uses inheritance
- [x] Inexhaustible source (SolarField) calls the super() function to inherit
- [ ] Inexhaustible source (WindFarm) calls the super() function to inherit

## Instantiation

- [ ] Exhaustible source (OilStation) calls Oil object
- [x] Exhaustible source (CoalStation) calls Oil object

## Methods

- [ ] Exhaustible source (OilStation) contains use method with correct signature
- [x] Exhaustible source (CoalStation) contains use method with correct signature

## Percent complete

Based on the checks achieved, this assignment is `50%` complete.
